### ISSUE TITLE
Кросспроверка

### ISSUE THREAD

**Issue by StarchenkovYaroslav** [IKBOstudent/homework_react#1]
## Критерии

- [x] Реализована страница списка фильмов
  - [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)
  - [x] Работает переход по клику на фильм(либо на всю карточку, либо на название или постер)
  - [x] Реализованы все ограничения и шаблоны ввода для фильтров(там где указаны)
  - [x] Реализованы ограничения на кол-во билетов
- [x] Фильтры
  - [x] Фильтрация работает - значения в списке фильтруются
- [x] Страница фильма
  - [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)
  - [x] Реализованы ограничения на кол-во билетов
- [x] Страница заказа
  - [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)
  - [x] Финальное кол-во билетов считается корректно
  - [x] Модально окно работает как описано
- [x] Страница о нас
  - [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)
  - [x] Static (страница генериться на билде, а не на реквесте)
- [x] Страница вопросы/ответы
  - [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)
  - [x] Static (страница генериться на билде, а не на реквесте)
- [x] Шапка
  - [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)
  - [x] Позиционируется липко(стики)
- [x] Футер
  - [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)
- [x] Модалка
  - [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)
  - [x] Используется портал
- [x] Стор
  - [x] Данные корректно разбиты на модули(пример - кинотеатры, фильмы, отзывы, авторы отзывов, корзина)
  - [x] Селекторы написаны оптимально(нет кучи дублирования)
  - [x] Данные грузятся только по необходимости(отзывы не надо грузить на странице списка фильмов и тд), если уже загружены, то повторно не загружаются.
- [ ] Оптимизация
  - [ ] При изменении кол-ва билетов не перерендеривается вся карточка фильма(в списке фильмов, на странице фильма, в заказе), а только часть с количеством
  **При изменении количества билетов перерендеривается весь компонент `MovieList` на странице поиска фильмов и весь компонент `CartPage` на странице корзины. Оба компонента подписаны на изменения объекта `cartItems`, который обновляется при каждом экшене корзины.**  
![2023-06-29_18-04-36](https://github.com/IKBOstudent/homework_react/assets/86304001/7eda1165-cc3b-4140-9a00-f382456d1f24)
![2023-06-29_18-05-38](https://github.com/IKBOstudent/homework_react/assets/86304001/27bf375a-8f8d-40af-a3d5-7c0f715a91c3)
**Селектор количества билетов можно расположить максимально близко к месту назначения - в компоненте управления количеством - и подписаться непосредственно на нужное число:**
    ```tsx
      export function CartTicketControlls({ id }: Props) {
        const count = useAppSelector((state) => state.cart.cartItems[id].count)

        ...
      }
    ```
  - [ ] Для картинок используется Image некста. Постеры(про список фильма), которые вне вьюпорта грузятся лениво
  **В компоненте `TicketCard` для `<Image />` использована опция `priority`, заставляющая грузиться сразу все изображения.**
  - [x] На полях фильтрации с свободным вводом есть debounce(фильтрация происходит только после окончания ввода)

## Доп. Комментарий:

**При обновлении счетчика корзины рендерится весь `Header`. Можно унести верстку с селектором числа билетов в отдельный компонент и обновлять только его.**

**Comment by markterris** [comment]
Спасибо за подробный отзыв. После дедлайна я уже переделал селекторы и стор и все что связано с лишними перерендерами. Жаль что не хватило времени и опыта сделать все сразу и быстро(. Насчет image некста спасибо за наводку, я просто один раз написал с priority и везде повставлял одинаково, пойду почитаю про это подробнее.
